/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TalkToSeniorRouteImport } from './routes/talk-to-senior'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogNewtonSchoolOfTechnologyOverviewRouteImport } from './routes/blog.newton-school-of-technology-overview'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BlogCollegeCollegeRouteImport } from './routes/blog.college.$college'
import { Route as BlogCategoryCategoryRouteImport } from './routes/blog.category.$category'

const TalkToSeniorRoute = TalkToSeniorRouteImport.update({
  id: '/talk-to-senior',
  path: '/talk-to-senior',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogNewtonSchoolOfTechnologyOverviewRoute =
  BlogNewtonSchoolOfTechnologyOverviewRouteImport.update({
    id: '/blog/newton-school-of-technology-overview',
    path: '/blog/newton-school-of-technology-overview',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCollegeCollegeRoute = BlogCollegeCollegeRouteImport.update({
  id: '/blog/college/$college',
  path: '/blog/college/$college',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategoryCategoryRoute = BlogCategoryCategoryRouteImport.update({
  id: '/blog/category/$category',
  path: '/blog/category/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/talk-to-senior': typeof TalkToSeniorRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/newton-school-of-technology-overview': typeof BlogNewtonSchoolOfTechnologyOverviewRoute
  '/blog/': typeof BlogIndexRoute
  '/blog/category/$category': typeof BlogCategoryCategoryRoute
  '/blog/college/$college': typeof BlogCollegeCollegeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/talk-to-senior': typeof TalkToSeniorRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/newton-school-of-technology-overview': typeof BlogNewtonSchoolOfTechnologyOverviewRoute
  '/blog': typeof BlogIndexRoute
  '/blog/category/$category': typeof BlogCategoryCategoryRoute
  '/blog/college/$college': typeof BlogCollegeCollegeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/talk-to-senior': typeof TalkToSeniorRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/newton-school-of-technology-overview': typeof BlogNewtonSchoolOfTechnologyOverviewRoute
  '/blog/': typeof BlogIndexRoute
  '/blog/category/$category': typeof BlogCategoryCategoryRoute
  '/blog/college/$college': typeof BlogCollegeCollegeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/talk-to-senior'
    | '/blog/$slug'
    | '/blog/newton-school-of-technology-overview'
    | '/blog/'
    | '/blog/category/$category'
    | '/blog/college/$college'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/talk-to-senior'
    | '/blog/$slug'
    | '/blog/newton-school-of-technology-overview'
    | '/blog'
    | '/blog/category/$category'
    | '/blog/college/$college'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/talk-to-senior'
    | '/blog/$slug'
    | '/blog/newton-school-of-technology-overview'
    | '/blog/'
    | '/blog/category/$category'
    | '/blog/college/$college'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TalkToSeniorRoute: typeof TalkToSeniorRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogNewtonSchoolOfTechnologyOverviewRoute: typeof BlogNewtonSchoolOfTechnologyOverviewRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BlogCategoryCategoryRoute: typeof BlogCategoryCategoryRoute
  BlogCollegeCollegeRoute: typeof BlogCollegeCollegeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/talk-to-senior': {
      id: '/talk-to-senior'
      path: '/talk-to-senior'
      fullPath: '/talk-to-senior'
      preLoaderRoute: typeof TalkToSeniorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/newton-school-of-technology-overview': {
      id: '/blog/newton-school-of-technology-overview'
      path: '/blog/newton-school-of-technology-overview'
      fullPath: '/blog/newton-school-of-technology-overview'
      preLoaderRoute: typeof BlogNewtonSchoolOfTechnologyOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/college/$college': {
      id: '/blog/college/$college'
      path: '/blog/college/$college'
      fullPath: '/blog/college/$college'
      preLoaderRoute: typeof BlogCollegeCollegeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/category/$category': {
      id: '/blog/category/$category'
      path: '/blog/category/$category'
      fullPath: '/blog/category/$category'
      preLoaderRoute: typeof BlogCategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TalkToSeniorRoute: TalkToSeniorRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogNewtonSchoolOfTechnologyOverviewRoute:
    BlogNewtonSchoolOfTechnologyOverviewRoute,
  BlogIndexRoute: BlogIndexRoute,
  BlogCategoryCategoryRoute: BlogCategoryCategoryRoute,
  BlogCollegeCollegeRoute: BlogCollegeCollegeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
